---
galaxy_info:
  author: Your Name
  description: A role to clone a dotfiles repository and symlink files for specified users.
  company: Your Company
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - dotfiles
    - configuration

dependencies: []