---
- name: Add Brave GPG key
  become: true
  ansible.builtin.get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: '0644'
    force: true

- name: Add Brave repository
  become: true
  ansible.builtin.apt_repository:
    repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg] https://brave-browser-apt-release.s3.brave.com/ stable main"
    state: present
    filename: brave-browser-release

- name: Install Brave browser
  become: true
  ansible.builtin.apt:
    name: brave-browser
    state: present
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time }}"

# ---
# - name: Install Brave browser
#   ansible.builtin.shell: curl -fsS  {{ brave_browser_download_url }} | sh
#   # Prevents tasks from running if found
#   args:
#     creates: /usr/bin/brave-browser
