#SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: jonimofo
  description: Creates system users from a list and configures passwordless sudo for the 'sudo' group.
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: EL
      versions:
        - "8"
        - "9"
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - system
    - users
    - accounts
    - security
    - sudo
dependencies: []