#SPDX-License-Identifier: MIT-0
---
galaxy_info:
  author: jonimofo
  description: Installs and configures the Uncomplicated Firewall (UFW) on Debian-based systems.
  license: MIT
  min_ansible_version: "2.12"
  platforms:
    - name: Debian
      versions:
        - bullseye
        - bookworm
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - security
    - firewall
    - system
    - networking
    - ufw
dependencies: []